# Generated by Django 3.0.4 on 2020-04-05 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200404_1350'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shoppingitem',
            unique_together={('UserID', 'PriceID')},
        ),
    ]
