# Generated by Django 3.0.4 on 2020-04-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200405_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='WordpressID',
            field=models.IntegerField(null=True),
        ),
    ]
