# Generated by Django 3.0.4 on 2020-04-11 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_product_wordpressid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserState',
            field=models.IntegerField(default=99),
        ),
    ]
