# Generated by Django 3.0.4 on 2020-04-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_user_userstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Userphonenumber',
            field=models.CharField(blank=True, db_column='UserPhoneNumber', max_length=40, unique=True),
        ),
    ]
