# Generated by Django 3.0.4 on 2020-04-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20200411_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='WordpressID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
