# Generated by Django 3.0.4 on 2020-04-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_user_usershopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='ShopLatitude',
            field=models.DecimalField(blank=True, db_column='ShopLatitude', decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='ShopLongitude',
            field=models.DecimalField(blank=True, db_column='ShopLongitude', decimal_places=8, max_digits=11, null=True),
        ),
    ]
