# Generated by Django 3.0.4 on 2020-04-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20200425_1307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('ShopID', 'ProductID')},
        ),
    ]
