# Generated by Django 3.0.4 on 2020-04-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20200425_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserMessenger',
            field=models.BooleanField(default=False),
        ),
    ]
